// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import _ from 'lodash'
import type { NextApiRequest, NextApiResponse } from 'next'

const data = [
  {
    id: '1',
    weight: 10,
    reps: 10,
    setNumber: 1,
    date: '2022-04-11T10:35:55.268Z',
    userId: '1',
    workoutLineId: '1',
    workoutLine: {
      id: '1',
      recWeight: 10,
      recSets: 3,
      recReps: 10,
      steps: 1,
      exerciseId: '1',
      workoutId: '1',
    },
  },
  {
    id: '2',
    weight: 10,
    reps: 10,
    setNumber: 1,
    date: '2022-04-11T10:35:55.268Z',
    userId: '1',
    workoutLineId: '2',
    workoutLine: {
      id: '2',
      recWeight: 10,
      recSets: 3,
      recReps: 10,
      steps: 2,
      exerciseId: '2',
      workoutId: '1',
    },
  },
  {
    id: '3',
    weight: 10,
    reps: 10,
    setNumber: 1,
    date: '2022-04-11T10:35:55.268Z',
    userId: '1',
    workoutLineId: '3',
    workoutLine: {
      id: '3',
      recWeight: 10,
      recSets: 3,
      recReps: 10,
      steps: 3,
      exerciseId: '3',
      workoutId: '1',
    },
  },
  {
    id: '4',
    weight: 11,
    reps: 10,
    setNumber: 1,
    date: '2022-04-13T19:35:55.268Z',
    userId: '1',
    workoutLineId: '1',
    workoutLine: {
      id: '1',
      recWeight: 10,
      recSets: 3,
      recReps: 10,
      steps: 1,
      exerciseId: '1',
      workoutId: '1',
    },
  },
  {
    id: '5',
    weight: 11,
    reps: 10,
    setNumber: 1,
    date: '2022-04-13T19:35:55.268Z',
    userId: '1',
    workoutLineId: '2',
    workoutLine: {
      id: '2',
      recWeight: 10,
      recSets: 3,
      recReps: 10,
      steps: 2,
      exerciseId: '2',
      workoutId: '1',
    },
  },
  {
    id: '6',
    weight: 11,
    reps: 10,
    setNumber: 1,
    date: '2022-04-13T19:35:55.268Z',
    userId: '1',
    workoutLineId: '3',
    workoutLine: {
      id: '3',
      recWeight: 10,
      recSets: 3,
      recReps: 10,
      steps: 3,
      exerciseId: '3',
      workoutId: '1',
    },
  },
  {
    id: '7',
    weight: 8,
    reps: 10,
    setNumber: 1,
    date: '2022-04-21T10:35:55.268Z',
    userId: '1',
    workoutLineId: '1',
    workoutLine: {
      id: '1',
      recWeight: 10,
      recSets: 3,
      recReps: 10,
      steps: 1,
      exerciseId: '1',
      workoutId: '1',
    },
  },
  {
    id: '8',
    weight: 8,
    reps: 10,
    setNumber: 1,
    date: '2022-04-21T10:35:55.268Z',
    userId: '1',
    workoutLineId: '2',
    workoutLine: {
      id: '2',
      recWeight: 10,
      recSets: 3,
      recReps: 10,
      steps: 2,
      exerciseId: '2',
      workoutId: '1',
    },
  },
  {
    id: '9',
    weight: 8,
    reps: 10,
    setNumber: 1,
    date: '2022-04-21T10:35:55.268Z',
    userId: '1',
    workoutLineId: '3',
    workoutLine: {
      id: '3',
      recWeight: 10,
      recSets: 3,
      recReps: 10,
      steps: 3,
      exerciseId: '3',
      workoutId: '1',
    },
  },
]
export default function handler(req: NextApiRequest, res: NextApiResponse) {
  const groupedData = _(data).groupBy((x) => x.workoutLine.exerciseId)
  res.status(200).json(groupedData)
}

https://api.whatsapp.com/send/?phone=%2B201066886707&text=Good+morning+Mina%0D%0A%0D%0AThis+is+a+reminder+that+all+application+%26+pre-course+submissions+are+due+TODAY+%28May+28th%29+in+order+to+be+considered+for+our+next+Full+Stack+Bootcamp+cohort+starting+on+June+19th.%0D%0AFind+the+pre-course+here%3A+precourse.tawwr.com%0D%0AIf+you+have+any+questions%2C+let+us+know%21%0D%0A%0D%0AThe+Tawwr+Team&app_absent=0
https://api.whatsapp.com/send/?phone=%2B201066886707?text=Good+morning+Mina%0D%0A%0D%0AThis+is+a+reminder+that+all+application+%26+pre-course+submissions+are+due+TODAY+%28May+28th%29+in+order+to+be+considered+for+our+next+Full+Stack+Bootcamp+cohort+starting+on+June+19th.%0D%0AFind+the+pre-course+here%3A+precourse.tawwr.com%0D%0AIf+you+have+any+questions%2C+let+us+know%21%0D%0A%0D%0AThe+Tawwr+Team&app_absent=0